(() => {
const TOTAL=1045;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PRESETS={dark:{bg:'#111315',paper:'#1a1b1c',text:'#e9e6df',font:'Georgia',size:20,lh:1.9,width:880,weight:400},paper:{bg:'#e8e1d5',paper:'#f8f3e8',text:'#3d352d',font:'Georgia',size:20,lh:1.9,width:880,weight:400},night:{bg:'#0c1219',paper:'#111b25',text:'#dcebf8',font:'Georgia',size:20,lh:1.95,width:880,weight:400}};
function settings(){try{return {...PRESETS.dark,...JSON.parse(localStorage.getItem('lb_settings')||'{}')}}catch{return {...PRESETS.dark}}}
function apply(v){document.documentElement.style.setProperty('--bg',v.bg);document.documentElement.style.setProperty('--reader',v.paper);document.documentElement.style.setProperty('--text',v.text);document.documentElement.style.setProperty('--font',v.font);document.documentElement.style.setProperty('--size',v.size+'px');document.documentElement.style.setProperty('--lh',v.lh);document.documentElement.style.setProperty('--max',v.width+'px');document.documentElement.style.setProperty('--weight',v.weight);localStorage.setItem('lb_settings',JSON.stringify(v));
[['fontSelect',v.font],['sizeRange',v.size],['lineRange',v.lh],['widthRange',v.width],['textColor',v.text],['bgColor',v.bg],['paperColor',v.paper],['weightSelect',v.weight]].forEach(([id,val])=>{const e=document.getElementById(id);if(e)e.value=val});
if($('#sizeOut'))$('#sizeOut').textContent=v.size+'px';if($('#lineOut'))$('#lineOut').textContent=Number(v.lh).toFixed(2);if($('#widthOut'))$('#widthOut').textContent=v.width+'px';}
function bindSettings(){const d=$('#settingsDialog');if(!d)return;apply(settings());$('#settingsBtn')?.addEventListener('click',()=>d.showModal());$('#quickSettings')?.addEventListener('click',()=>d.showModal());document.querySelectorAll('.preset').forEach(b=>b.addEventListener('click',()=>apply({...PRESETS[b.dataset.preset]})));$('#resetSettings')?.addEventListener('click',()=>apply({...PRESETS.dark}));['fontSelect','sizeRange','lineRange','widthRange','textColor','bgColor','paperColor','weightSelect'].forEach(id=>document.getElementById(id)?.addEventListener('input',()=>{const s=settings();apply({...s,font:$('#fontSelect')?.value||s.font,size:Number($('#sizeRange')?.value||s.size),lh:Number($('#lineRange')?.value||s.lh),width:Number($('#widthRange')?.value||s.width),text:$('#textColor')?.value||s.text,bg:$('#bgColor')?.value||s.bg,paper:$('#paperColor')?.value||s.paper,weight:Number($('#weightSelect')?.value||s.weight)})}));}
function openChapter(id){const n=Math.min(TOTAL,Math.max(1,Number(id)||1));localStorage.setItem('lb_chapter',n);location.href='reader.html?chapter='+n}
function loadScript(src){return new Promise((res,rej)=>{window.CHAPTER_DATA=null;window.__LB_CHAPTER__=null;const s=document.createElement('script');s.src=src;s.onload=()=>{const data=window.CHAPTER_DATA||window.__LB_CHAPTER__;data?res(data):rej(new Error('Dữ liệu chương trống'));};s.onerror=()=>rej(new Error('Không mở được file dữ liệu chương '+src));document.head.appendChild(s)})}
function bodyHtml(t){return String(t||'').replace(/\r\n/g,'\n').split(/\n\s*\n+/).filter(Boolean).map(p=>`<p>${esc(p).replace(/\n/g,' ')}</p>`).join('')}
async function indexPage(){bindSettings();let chapters=Array.isArray(window.CHAPTERS_INDEX)?window.CHAPTERS_INDEX:(Array.isArray(window.__LB_INDEX__)?window.__LB_INDEX__:Array.from({length:TOTAL},(_,i)=>({id:i+1,title_vi:''})));
$('#heroCount')&&($('#heroCount').textContent=chapters.length);$('#countBadge')&&($('#countBadge').textContent=chapters.length);const list=$('#chapterList');function render(q=''){const query=q.trim().toLowerCase();list.innerHTML=chapters.filter(c=>!query||`${c.id} ${c.title_vi||''} ${c.title_zh||''}`.toLowerCase().includes(query)).map(c=>`<a class="chapter-item" href="reader.html?chapter=${c.id}"><div class="chapter-number">CHƯƠNG ${c.id}</div><div class="chapter-name">${esc(c.title_vi||c.title_zh||'')}</div></a>`).join('');$('#resultCount').textContent=query?`${list.children.length} kết quả`:`${chapters.length} chương`}
render();$('#chapterSearch')?.addEventListener('input',e=>render(e.target.value));$('#readStart')?.addEventListener('click',()=>openChapter(1));$('#readLast')?.addEventListener('click',()=>openChapter(localStorage.getItem('lb_chapter')||1));$('#jumpTop')?.addEventListener('click',()=>{$('#jumpDialog').showModal();$('#jumpInput').focus()});$('#jumpGo')?.addEventListener('click',()=>openChapter($('#jumpInput').value));$('#jumpInput')?.addEventListener('keydown',e=>e.key==='Enter'&&openChapter(e.target.value));$('#chaptersBtn')?.addEventListener('click',()=>$('#sidebar')?.scrollIntoView({behavior:'smooth'}));const sel=$('#chapterSelect');if(sel){sel.innerHTML=chapters.map(c=>`<option value="${c.id}">Chương ${c.id} · ${esc(c.title_vi||c.title_zh||'')}</option>`).join('');sel.value=String(localStorage.getItem('lb_chapter')||1);sel.addEventListener('change',e=>openChapter(e.target.value));}}
async function readerPage(){bindSettings();const id=Math.min(TOTAL,Math.max(1,Number(new URLSearchParams(location.search).get('chapter')||localStorage.getItem('lb_chapter')||1)||1));$('#chapterTitle').textContent='Đang tải…';try{const c=await loadScript(`data/chapters_vi_js/${id}.js`);const title=c.title_vi||`Chương ${id}`;document.title=title+' · Lam Bạch Xã';$('#readingTopTitle').textContent=title;$('#chapterKicker').textContent='CHƯƠNG '+id;$('#chapterTitle').textContent=title;let sourceMode=false;const render=()=>{const show=sourceMode&&c.body_zh;$('#chapterTitle').textContent=show?(c.title_zh||title):title;$('#readingTopTitle').textContent=show?(c.title_zh||title):title;$('#readerText').innerHTML=bodyHtml(show?c.body_zh:c.body_vi);const b=$('#sourceToggle');if(b)b.textContent=show?'🇻🇳 Bản dịch':'文 中文原文'};render();$('#sourceToggle')?.addEventListener('click',()=>{sourceMode=!sourceMode;render()});const p=id>1?id-1:null,n=id<TOTAL?id+1:null;[['prevBtn',p],['prevBottom',p],['nextBtn',n],['nextBottom',n]].forEach(([id,target])=>{const e=$('#'+id);if(!e)return;e.disabled=!target;e.onclick=target?()=>openChapter(target):null});localStorage.setItem('lb_chapter',id);requestAnimationFrame(()=>window.scrollTo(0,0))}catch(e){$('#chapterTitle').textContent='Không thể tải chương';$('#readingTopTitle').textContent='Lỗi tải chương';$('#readerText').innerHTML=`<div class="error-state"><h3>${esc(e.message)}</h3><p>Bản STATIC này không cần chạy server hoặc BAT. Hãy giữ nguyên thư mục <b>data/chapters_vi_js</b> cùng với <b>reader.html</b>.</p></div>`}
$('#quickMinus')?.addEventListener('click',()=>{const s=settings();apply({...s,size:Math.max(14,s.size-1)})});$('#quickPlus')?.addEventListener('click',()=>{const s=settings();apply({...s,size:Math.min(34,s.size+1)})});addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;if(e.key==='ArrowLeft'&&id>1)openChapter(id-1);if(e.key==='ArrowRight'&&id<TOTAL)openChapter(id+1)});}
document.addEventListener('DOMContentLoaded',()=>document.body.classList.contains('reader-page')?readerPage():indexPage());
})();